services:
  - type: web
    name: studytube-ai-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: GOOGLE_GEMINI_API_KEY
        scope: all
        value: AIzaSyBK6O7Fu2_4TF-VJnoJArffhAOicKQL8uQ
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: static_site
    name: studytube-ai-frontend
    plan: free
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        scope: all
        value: https://studytube-ai-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        scope: all
        value: AIzaSyBYM1XdXXNqOqOEueigNtF03GJUhoMmz2E
      - key: VITE_FIREBASE_AUTH_DOMAIN
        scope: all
        value: studytube-ai-82345.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        scope: all
        value: studytube-ai-82345
      - key: VITE_FIREBASE_STORAGE_BUCKET
        scope: all
        value: studytube-ai-82345.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        scope: all
        value: "413543712470"
      - key: VITE_FIREBASE_APP_ID
        scope: all
        value: 1:413543712470:web:550e60d4be02a722286b77
